name: AreaSounds
main: com.plexon21.AreaSounds.AreaSounds
version: 1.0
commands:
   playAreaSound:
      description: Play a specific sound, returns the id of the sound.
      usage: /playAreaSound name volume(float) pitch(float) radius(int) x(float) y(float) z(float) loop(true/false) [player1] [player2]....
   stopAreaSound:
      description: This command stops a specific task or all if no id is given
      usage: /stopAreaSound taskID
   saveAreaSound:
      description: Saves all running looped sounds into file.
      usage: /saveAreaSound